<a href="https://colab.research.google.com/github/2303a52068/GENERATIVE-AI-2025/blob/main/GEN_AI_ASSIGNMENT_1_%202Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score, f1_score, confusion_matrix,recall_score,precision_score

# Regression Metrics
y_actual_classification = np.array([0,  1,  2,
                                     0,  1,  2,
                                     0,  1,  2,
                                     0,  1,  2,
                                     0,  1,  2 ])

y_pred_classification = np.array([ 0,  1,  0,
                                    0, 0,  0,
                                    1, 2,  1,
                                    2, 0,  2,
                                    2, 2,  2])

# Calculate evaluation metrics for classification
accuracy = accuracy_score(y_actual_classification, y_pred_classification)
f1 = f1_score(y_actual_classification, y_pred_classification, average='weighted')
confusion = confusion_matrix(y_actual_classification, y_pred_classification)
recall = recall_score(y_actual_classification, y_pred_classification, average='weighted')
precision = precision_score(y_actual_classification, y_pred_classification,average='weighted')

print("\nClassification Metrics:")
print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Confusion Matrix:\n", confusion)
print("Recall Score:", recall)
print("Precision Score:", precision)


Classification Metrics:
Accuracy: 0.3333333333333333
F1 Score: 0.3257575757575758
Confusion Matrix:
 [[2 1 2]
 [2 1 2]
 [2 1 2]]
Recall Score: 0.3333333333333333
Precision Score: 0.3333333333333333
